### ISSUE TITLE
Have an explicit S3 sync session start and S3 sync session end

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/record-and-upload#16]
We want to also capture a RecorderStopped event by monitoring updates to "last_sync_stop.txt".

In order to detect the RecorderStarted event, we monitor changed to the "last_sync_start.txt" file which is a side-effect of the `testUploadPermissions()` method.
We want to also capture 

Instead of relying on this, we should rename `testUploadPermissions()` to `startS3SyncSession()` and have an equivalent method called `stopS3SyncSession()` with touches an equivalent "last_sync_stop.txt" file.

**Comment by neomatrix369** [comment]
I'll take a look at the code to find out where what is happening, does not immediately appear clear to me, but maybe I need more context to understand whats going on.
