### ISSUE TITLE
[Enhancement] Should be able to run the app without an S3 account

### ISSUE THREAD

**Issue by neomatrix369** [julianghionoiu/record-and-upload#4]
For testing purposes or first-time usage (developer feature/developer environment), we should be able to pass it a dummy directory where and bypass AWS S3 credential checks.

**Comment by julianghionoiu** [comment]
This component has been manually tested, it is just an aggregator of multiple projects. The AWS upload is one of the main responsibility of this executable so I want to get as much coverage as possible. (even if this means an extra setup step)
