### ISSUE TITLE
Investigate other packaging options

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/record-and-upload#6]
The current pain points are:
- the recording scripts tend to break with newer Java releases
- the user has to install Java before starting the app, which is annoying if you come from a different language, say Python
- it interacts with the Maven system on the box and that might have different settings

The good things about the current approach, which we should take care not to degrade:
- it is multi-platform, same code is being run on all the major operating systems with minimal differences, except the fact that it bundle native ffmpeg libraries
- the size of the initial jar is very small (capsule), which makes it easy to deploy via Git
- the capsule caches the downloaded libraries so that the next time it runs it does not have to do anything

**Comment by neomatrix369** [comment]
We can potentially downgrade this task, given the issue with #5 was a minor one, some sort of oversight on our part

**Comment by julianghionoiu** [comment]
Still worth enumerating the options

**Comment by julianghionoiu** [comment]
Let's time-box this to a week.

**Comment by julianghionoiu** [comment]
Closing this issue.
We have moved past investigation and into implementation.
