### ISSUE TITLE
Java 11 and 12 fail to run record-and-upload

### ISSUE THREAD

**Issue by neomatrix369** [julianghionoiu/record-and-upload#7]
Not like #5 but the new releases of Java 11 and 12 give the below outputs when the `record_screen_and_upload.bat` file I run. This issue isn't OS specific but more Java version specific.

*Java 11*

```
D:\tdl-runner-java>record_screen_and_upload.bat

Displaying operating system specific systeminfo...
Loading Hotfix Information ...
OS Name:                   Microsoft Windows 10 Enterprise Evaluation
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              innotek GmbH VirtualBox, 12/1/2006

JAVA_HOME=C:\PROGRA~1\Java\JDK-11~1.1

JAVA_EXE=C:\PROGRA~1\Java\JDK-11~1.1\bin\java.exe

D:\tdl-runner-java>for /F "tokens=3" %g in ('C:\PROGRA~1\Java\JDK-11~1.1\bin\java.exe -version 2>&1 | findstr /i "version"') do (set JAVA_FULL_VERSION=%g )

D:\tdl-runner-java>(set JAVA_FULL_VERSION="11.0.1" )

JAVA_FULL_VERSION=11.0.1

JAVA_VERSION=11
"--- Java 9 or higher detected (Java version 11) ---"
"Adding JVM args to the DEFAULT_JVM_OPTS variable, new value set to ''"
"--------------------------------------------------------------------------------------------------------------"

D:\tdl-runner-java>"C:\PROGRA~1\Java\JDK-11~1.1\bin\java.exe" --illegal-access=warn --add-modules=java.xml.bind,java.activation    -jar "D:\tdl-runner-java\\record\record-and-upload-capsule.jar" --config D:\tdl-runner-java\\config\credentials.config --store D:\tdl-runner-java\\record\localstore --sourcecode D:\tdl-runner-java\

Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
```

*Java 12*

```
Java 12
D:\tdl-runner-java>record_screen_and_upload.bat

Displaying operating system specific systeminfo...
OS Name:                   Microsoft Windows 10 Enterprise Evaluation
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              innotek GmbH VirtualBox, 12/1/2006

JAVA_HOME=C:\PROGRA~1\Java\jdk-12

JAVA_EXE=C:\PROGRA~1\Java\jdk-12\bin\java.exe

D:\tdl-runner-java>for /F "tokens=3" %g in ('C:\PROGRA~1\Java\jdk-12\bin\java.exe -version 2>&1 | findstr /i "version"') do (set JAVA_FULL_VERSION=%g )

D:\tdl-runner-java>(set JAVA_FULL_VERSION="12-ea" )

JAVA_FULL_VERSION=12-ea

JAVA_VERSION=12-ea
"--- Java 9 or higher detected (Java version 12-ea) ---"
"Adding JVM args to the DEFAULT_JVM_OPTS variable, new value set to '--illegal-access=warn --add-modules=java.xml.bind,java.activation '"
"--------------------------------------------------------------------------------------------------------------"

D:\tdl-runner-java>"C:\PROGRA~1\Java\jdk-12\bin\java.exe" --illegal-access=warn --add-modules=java.xml.bind,java.activation    -jar "D:\tdl-runner-java\\record\record-and-upload-capsule.jar" --config D:\tdl-runner-java\\config\credentials.config --store D:\tdl-runner-java\\record\localstore --sourcecode D:\tdl-runner-java\
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
```

We need to check if the error is due to renaming of the packages or total removal or removal of the kill switch.

**Comment by neomatrix369** [comment]
Should we go for a short/quick fix for the above or focus on #6 instead?

**Comment by julianghionoiu** [comment]
I guess we need to investigate whether it is possible to disable the module checking (quick fix). That will buy us more time so that we can focus on #6

**Comment by neomatrix369** [comment]
It's not the not something we can disable, those modules are dependencies of the modules in the root project and need resolving - either we find the correct way to resolve it starting version 11 or look at other alternatives in case it is not support starting version 11

**Comment by neomatrix369** [comment]
Here is what I meant https://jaxenter.com/jdk-11-java-ee-modules-140674.html

EoL for `java.xml.bind`!!!!

But luckily we have a fix in https://blog.codefx.org/java/java-11-migration-guide/ - will need to apply this to the build script, rebuild the jar and re-run them in both java 11 and 12

Going thru it I can see its just the removal of the Java EE modules from Java SE is causing the above,

**Comment by julianghionoiu** [comment]
Ok, so if we understand our use of it and find alternatives, then we should be good, right?

**Comment by neomatrix369** [comment]
Hmm alternatives for the libraries that depend on `java.xml.bind` etc? Yes in theory we could.

**Comment by julianghionoiu** [comment]
Let run an audit first and see which libraries depend on `java.xml.bind` etc. Then we can make the call.

**Comment by neomatrix369** [comment]
[record-and-upload-jdeps-report.zip](https://github.com/julianghionoiu/record-and-upload/files/2592189/record-and-upload-jdeps-report.zip), look for these lines in the attached report (generated using jdeps):

```java
org.eclipse.jgit-4.8.0.201706111038-r.jar -> java.xml.bind (java.xml.bind)
        org.eclipse.jgit.transport.WalkEncryption$SymmetricEncryption -> javax.xml.bind.DatatypeConverter                   
        org.eclipse.jgit.transport.WalkEncryption$Vals     -> javax.xml.bind.DatatypeConverter 
aws-java-sdk-core-1.11.127.jar -> java.xml.bind (java.xml.bind)
        com.amazonaws.util.Base64                          -> javax.xml.bind.DatatypeConverter                   
        com.amazonaws.util.Base64                          -> javax.xml.bind.JAXBContext                         
        com.amazonaws.util.Base64                          -> javax.xml.bind.JAXBException 

```

The above two jars depend on it, and its normal for these Java EE modules to linger about, we can't really get rid of them, they are inherent with the old Java packaging architecture.

I have added a gradle task to generate the above report and also added some examples on how to get them via CLI inside the .gradle file.

**Comment by neomatrix369** [comment]
Fix applied via https://github.com/julianghionoiu/tdl-lord-of-runners/pulls

**Comment by julianghionoiu** [comment]
Have you seen these references?
https://github.com/aws/aws-sdk-java/issues/1092
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

They reckon that if we add that dependency to the class-path it will work for all versions.
That means we can remove the complexity of selecting the right command line parameters

**Comment by neomatrix369** [comment]
Done, see https://github.com/julianghionoiu/tdl-lord-of-runners/pull/8#discussion_r234436877

**Comment by neomatrix369** [comment]
Closing as fixed via https://github.com/julianghionoiu/tdl-lord-of-runners/pull/8
